name: maisevento
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.18.0 <3.0.0'

# Add regular dependencies here.
dependencies:
  lucid_validation: ^1.0.1
  shelf_router: ^1.1.4
  mongo_dart: ^0.10.3
  bcrypt: ^1.1.3
  path: ^1.8.0
  jaguar_jwt: ^3.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
